/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.library_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aruna
 */
public class employee_supplier_book_details extends javax.swing.JFrame {

     Connection con;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
     
    /**
     * Creates new form supplier_book_details
     */
    public employee_supplier_book_details() {
        initComponents();
         try{
                Class.forName("oracle.jdbc.OracleDriver");
                //JOptionPane.showMessageDialog(this,"Driver Loaded!");
                try {
                       con = DriverManager.getConnection("jdbc:oracle:thin:@ArunaDevi:1522:orcl","scott","anssggah");
                        //JOptionPane.showMessageDialog(this,"Connected to Oracle database!");
                    }
                catch (SQLException ex) {
                        Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE,null, ex);
                        JOptionPane.showMessageDialog(this,ex.getMessage());
                    }
            }
            catch(ClassNotFoundException ex){
                    Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE,null, ex);
                    JOptionPane.showMessageDialog(this,ex.getMessage());
            }  
         display_supplier_book_details();
    }
    
    public void display_supplier_book_details()
    {
        int c;
        
        try{
            ps=con.prepareStatement("select * from supplier_book_details");
            rs=ps.executeQuery();
            
            ResultSetMetaData rsd=rs.getMetaData();
            c=rsd.getColumnCount();
            
            DefaultTableModel d=(DefaultTableModel)supplier_book_details_table.getModel();
            d.setRowCount(0);
            
            while (rs.next())
            {
                Vector v2=new Vector();
                
                for (int i=0;i<=c;i++)
                {
                    v2.add(rs.getString("s_id"));
                    v2.add(rs.getString("book_id"));
                    v2.add(rs.getString("branch_id"));
                    v2.add(rs.getString("supplied_date"));
                    v2.add(rs.getString("stock"));
                    v2.add(rs.getString("cost"));
                }
                
                d.addRow(v2);
            }
            //JOptionPane.showMessageDialog(this,"DISPLAYED!");
            
        }
        catch(SQLException ex)
        {
             Logger.getLogger(employee_supplier_book_details.class.getName()).log(Level.SEVERE,null, ex);
             JOptionPane.showMessageDialog(this,ex.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        branch_book_details_label = new javax.swing.JLabel();
        supplier_book_supplier_label = new javax.swing.JLabel();
        supplier_book_label = new javax.swing.JLabel();
        supplier_book_branch_label = new javax.swing.JLabel();
        supplier_book_supplied_date_label = new javax.swing.JLabel();
        supplier_book_stock_label = new javax.swing.JLabel();
        supplier_book_cost_label = new javax.swing.JLabel();
        supplier_book_supplier_id = new javax.swing.JTextField();
        supplier_book_book_id = new javax.swing.JTextField();
        supplier_book_branch_id = new javax.swing.JTextField();
        supplier_book_supplied_date = new javax.swing.JTextField();
        supplier_book_stock = new javax.swing.JTextField();
        supplier_book_cost = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        supplier_book_details_table = new javax.swing.JTable();
        supplier_book_search = new javax.swing.JButton();
        supplier_book_display = new javax.swing.JButton();
        supplier_book_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        branch_book_details_label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        branch_book_details_label.setText("     SUPPLIER BOOK DETAILS");

        supplier_book_supplier_label.setText("Supplier_id");

        supplier_book_label.setText("Book id");

        supplier_book_branch_label.setText("Branch id");

        supplier_book_supplied_date_label.setText("Supplied date");

        supplier_book_stock_label.setText("Stock");

        supplier_book_cost_label.setText("Cost");

        supplier_book_supplier_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_book_supplier_idActionPerformed(evt);
            }
        });

        supplier_book_details_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S_id", "book_id", "branch_id", "supplied_date", "stock", "cost"
            }
        ));
        supplier_book_details_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplier_book_details_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(supplier_book_details_table);

        supplier_book_search.setText("SEARCH");
        supplier_book_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_book_searchActionPerformed(evt);
            }
        });

        supplier_book_display.setText("DISPLAY");
        supplier_book_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_book_displayActionPerformed(evt);
            }
        });

        supplier_book_exit.setText("EXIT");
        supplier_book_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_book_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(branch_book_details_label, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(supplier_book_supplier_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(supplier_book_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(supplier_book_branch_label)
                        .addComponent(supplier_book_supplied_date_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(supplier_book_stock_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(supplier_book_cost_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supplier_book_supplied_date)
                    .addComponent(supplier_book_stock)
                    .addComponent(supplier_book_cost)
                    .addComponent(supplier_book_supplier_id, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplier_book_book_id)
                    .addComponent(supplier_book_branch_id))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(supplier_book_display)
                        .addGap(33, 33, 33)
                        .addComponent(supplier_book_search))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(supplier_book_exit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(branch_book_details_label)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supplier_book_supplier_label)
                            .addComponent(supplier_book_supplier_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supplier_book_label)
                            .addComponent(supplier_book_book_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplier_book_branch_label)
                            .addComponent(supplier_book_branch_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supplier_book_supplied_date_label)
                            .addComponent(supplier_book_supplied_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplier_book_stock_label)
                            .addComponent(supplier_book_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplier_book_cost_label)
                            .addComponent(supplier_book_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplier_book_search)
                    .addComponent(supplier_book_display))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(supplier_book_exit))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void supplier_book_supplier_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_book_supplier_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplier_book_supplier_idActionPerformed

    private void supplier_book_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_book_exitActionPerformed
        // TODO add your handling code here: 
        MainForm m=new MainForm();
            this.hide();
            m.setVisible(true);
    }//GEN-LAST:event_supplier_book_exitActionPerformed

    private void supplier_book_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_book_displayActionPerformed
        // TODO add your handling code here:
        display_supplier_book_details();
    }//GEN-LAST:event_supplier_book_displayActionPerformed

       
    
    private void supplier_book_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_book_searchActionPerformed
        
        int c;
        DefaultTableModel d1=(DefaultTableModel)supplier_book_details_table.getModel();
        int selectIndex = supplier_book_details_table.getSelectedRow();
        
        try {
             // TODO add your handling code here:
             String sql="select * from supplier_book_details where s_id=? and book_id=? and branch_id=?";
             ps=con.prepareStatement(sql);
             ps.setString(1,supplier_book_supplier_id.getText());
             ps.setString(2,supplier_book_book_id.getText());
             ps.setString(3,supplier_book_branch_id.getText());
             rs=ps.executeQuery();
             
             ResultSetMetaData rsd=rs.getMetaData();
            c=rsd.getColumnCount();
            
            DefaultTableModel d=(DefaultTableModel)supplier_book_details_table.getModel();
            d.setRowCount(0);
            
            while (rs.next())
            {
                Vector v2=new Vector();
                
                for (int i=0;i<=c;i++)
                {
                    v2.add(rs.getString("s_id"));
                    v2.add(rs.getString("book_id"));
                    v2.add(rs.getString("branch_id"));
                    v2.add(rs.getString("supplied_date"));
                    v2.add(rs.getString("stock"));
                    v2.add(rs.getString("cost"));
                }
                
                d.addRow(v2);
            }
             
             
         } catch (SQLException ex) {
             Logger.getLogger(employee_supplier_book_details.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_supplier_book_searchActionPerformed

    private void supplier_book_details_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_book_details_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel d1=(DefaultTableModel)supplier_book_details_table.getModel();
        int selectIndex = supplier_book_details_table.getSelectedRow();
        
        String S_id=d1.getValueAt(selectIndex,0).toString();
        supplier_book_supplier_id.setText(S_id);
        supplier_book_book_id.setText(d1.getValueAt(selectIndex,1).toString());
        supplier_book_branch_id.setText(d1.getValueAt(selectIndex,2).toString());
        supplier_book_supplied_date.setText(d1.getValueAt(selectIndex,3).toString());
        supplier_book_stock.setText(d1.getValueAt(selectIndex,4).toString());
        supplier_book_cost.setText(d1.getValueAt(selectIndex,5).toString());
    }//GEN-LAST:event_supplier_book_details_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee_supplier_book_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee_supplier_book_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee_supplier_book_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee_supplier_book_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee_supplier_book_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel branch_book_details_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField supplier_book_book_id;
    private javax.swing.JTextField supplier_book_branch_id;
    private javax.swing.JLabel supplier_book_branch_label;
    private javax.swing.JTextField supplier_book_cost;
    private javax.swing.JLabel supplier_book_cost_label;
    private javax.swing.JTable supplier_book_details_table;
    private javax.swing.JButton supplier_book_display;
    private javax.swing.JButton supplier_book_exit;
    private javax.swing.JLabel supplier_book_label;
    private javax.swing.JButton supplier_book_search;
    private javax.swing.JTextField supplier_book_stock;
    private javax.swing.JLabel supplier_book_stock_label;
    private javax.swing.JTextField supplier_book_supplied_date;
    private javax.swing.JLabel supplier_book_supplied_date_label;
    private javax.swing.JTextField supplier_book_supplier_id;
    private javax.swing.JLabel supplier_book_supplier_label;
    // End of variables declaration//GEN-END:variables
}
