/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.library_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aruna
 */
public class supply_source extends javax.swing.JFrame {

    Connection con;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    
    /**
     * Creates new form supply_source
     */
    public supply_source() {
        initComponents();
        try{
                Class.forName("oracle.jdbc.OracleDriver");
                //JOptionPane.showMessageDialog(this,"Driver Loaded!");
                try {
                       con = DriverManager.getConnection("jdbc:oracle:thin:@ArunaDevi:1522:orcl","scott","anssggah");
                        //JOptionPane.showMessageDialog(this,"Connected to Oracle database!");
                    }
                catch (SQLException ex) {
                        Logger.getLogger(supply_source.class.getName()).log(Level.SEVERE,null, ex);
                        JOptionPane.showMessageDialog(this,ex.getMessage());
                    }
            }
            catch(ClassNotFoundException ex){
                    Logger.getLogger(supply_source.class.getName()).log(Level.SEVERE,null, ex);
                    JOptionPane.showMessageDialog(this,ex.getMessage());
            }  
         display_supply_source();
    }

    
    public void display_supply_source()
    {
        int c;
        
        try{
            ps=con.prepareStatement("select * from supply_source");
            rs=ps.executeQuery();
            
            ResultSetMetaData rsd=rs.getMetaData();
            c=rsd.getColumnCount();
            
            DefaultTableModel d=(DefaultTableModel)supply_source_table.getModel();
            d.setRowCount(0);
            
            while (rs.next())
            {
                Vector v2=new Vector();
                
                for (int i=0;i<=c;i++)
                {
                    v2.add(rs.getString("branch_id"));
                    v2.add(rs.getString("book_id"));
                    v2.add(rs.getString("s_id"));
                }
                
                d.addRow(v2);
            }
            //JOptionPane.showMessageDialog(this,"DISPLAYED!");
            
        }
        catch(SQLException ex)
        {
             Logger.getLogger(supply_source.class.getName()).log(Level.SEVERE,null, ex);
             JOptionPane.showMessageDialog(this,ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        supply_source_branch_id_label = new javax.swing.JLabel();
        supply_source_book_id_label = new javax.swing.JLabel();
        supply_source_s_id_label = new javax.swing.JLabel();
        supply_source_branch_id = new javax.swing.JTextField();
        supply_source_book_id = new javax.swing.JTextField();
        supply_source_s_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        supply_source_table = new javax.swing.JTable();
        supply_source_display = new javax.swing.JButton();
        supply_source_search = new javax.swing.JButton();
        supply_source_exit = new javax.swing.JButton();
        supply_source_ckear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("    SUPPLY SOURCE");

        supply_source_branch_id_label.setText("branch id");

        supply_source_book_id_label.setText("Book id");

        supply_source_s_id_label.setText("S_id");

        supply_source_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Branch id", "Book id", "Supplier id"
            }
        ));
        supply_source_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supply_source_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(supply_source_table);

        supply_source_display.setText("DISPLAY");
        supply_source_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supply_source_displayActionPerformed(evt);
            }
        });

        supply_source_search.setText("SEARCH");
        supply_source_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supply_source_searchActionPerformed(evt);
            }
        });

        supply_source_exit.setText("EXIT");
        supply_source_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supply_source_exitActionPerformed(evt);
            }
        });

        supply_source_ckear.setText("CLEAR");
        supply_source_ckear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supply_source_ckearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supply_source_branch_id_label)
                            .addComponent(supply_source_s_id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supply_source_book_id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(supply_source_branch_id, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(supply_source_book_id)
                            .addComponent(supply_source_s_id)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(supply_source_search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(supply_source_exit))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(supply_source_display)
                                .addGap(28, 28, 28)
                                .addComponent(supply_source_ckear)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supply_source_branch_id_label)
                            .addComponent(supply_source_branch_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supply_source_book_id_label)
                            .addComponent(supply_source_book_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supply_source_s_id_label)
                            .addComponent(supply_source_s_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supply_source_ckear)
                            .addComponent(supply_source_display)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supply_source_search)
                    .addComponent(supply_source_exit))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    
    private void supply_source_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supply_source_searchActionPerformed
        // TODO add your handling code here:
        
        int c;
        DefaultTableModel d1=(DefaultTableModel)supply_source_table.getModel();
        int selectIndex = supply_source_table.getSelectedRow();
        
        try {
             // TODO add your handling code here:
             String sql="select * from supply_source where branch_id=? and book_id=? and s_id=?";
             ps=con.prepareStatement(sql);
             ps.setString(1,supply_source_branch_id.getText());
             ps.setString(2,supply_source_book_id.getText());
             ps.setString(3,supply_source_s_id.getText());
             rs=ps.executeQuery();
             
             ResultSetMetaData rsd=rs.getMetaData();
             c=rsd.getColumnCount();
            
            DefaultTableModel d=(DefaultTableModel)supply_source_table.getModel();
            d.setRowCount(0);
            
            while (rs.next())
            {
                Vector v2=new Vector();
                
                for (int i=0;i<=c;i++)
                {
                    
                    v2.add(rs.getString("branch_id"));
                    v2.add(rs.getString("book_id"));
                    v2.add(rs.getString("s_id"));
                }
                
                d.addRow(v2);
            }
             
             
         } catch (SQLException ex) {
             Logger.getLogger(supply_source.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_supply_source_searchActionPerformed

    private void supply_source_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supply_source_displayActionPerformed
        // TODO add your handling code here:
        display_supply_source();
    }//GEN-LAST:event_supply_source_displayActionPerformed

                
    
    private void supply_source_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supply_source_exitActionPerformed
        // TODO add your handling code here:
        MainForm m=new MainForm();
            this.hide();
            m.setVisible(true);
    }//GEN-LAST:event_supply_source_exitActionPerformed

    private void supply_source_ckearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supply_source_ckearActionPerformed
        // TODO add your handling code here:
        supply_source_branch_id.setText("");
        supply_source_book_id.setText("");
        supply_source_s_id.setText("");
    }//GEN-LAST:event_supply_source_ckearActionPerformed

    private void supply_source_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supply_source_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel d1=(DefaultTableModel)supply_source_table.getModel();
        int selectIndex = supply_source_table.getSelectedRow();
        
        String br_id=d1.getValueAt(selectIndex,0).toString();
        supply_source_branch_id.setText(br_id);
        supply_source_book_id.setText(d1.getValueAt(selectIndex,1).toString());
        supply_source_s_id.setText(d1.getValueAt(selectIndex,2).toString());
    }//GEN-LAST:event_supply_source_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supply_source.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supply_source.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supply_source.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supply_source.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supply_source().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField supply_source_book_id;
    private javax.swing.JLabel supply_source_book_id_label;
    private javax.swing.JTextField supply_source_branch_id;
    private javax.swing.JLabel supply_source_branch_id_label;
    private javax.swing.JButton supply_source_ckear;
    private javax.swing.JButton supply_source_display;
    private javax.swing.JButton supply_source_exit;
    private javax.swing.JTextField supply_source_s_id;
    private javax.swing.JLabel supply_source_s_id_label;
    private javax.swing.JButton supply_source_search;
    private javax.swing.JTable supply_source_table;
    // End of variables declaration//GEN-END:variables
}
