/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.library_project;

/**
 *
 * @author aruna
 */
public class UserForm extends javax.swing.JFrame {

    /**
     * Creates new form UserForm
     */
    public UserForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        user_navigation_branch = new javax.swing.JButton();
        user_navigation_book_details = new javax.swing.JButton();
        user_navigation_branch_book_details = new javax.swing.JButton();
        user_navigation_book = new javax.swing.JButton();
        user_navigation_author = new javax.swing.JButton();
        user_navigation_books_lent = new javax.swing.JButton();
        user_navigation_GO_BACK = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        jLabel1.setText("USER NAVIGATION");

        user_navigation_branch.setText("BRANCH");
        user_navigation_branch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_navigation_branchActionPerformed(evt);
            }
        });

        user_navigation_book_details.setText("BOOK_DETAILS");
        user_navigation_book_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_navigation_book_detailsActionPerformed(evt);
            }
        });

        user_navigation_branch_book_details.setText("BRANCH_BOOK_DETAILS");
        user_navigation_branch_book_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_navigation_branch_book_detailsActionPerformed(evt);
            }
        });

        user_navigation_book.setText("FINES");
        user_navigation_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_navigation_bookActionPerformed(evt);
            }
        });

        user_navigation_author.setText("AUTHOR");
        user_navigation_author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_navigation_authorActionPerformed(evt);
            }
        });

        user_navigation_books_lent.setText("BOOKS_LENT");
        user_navigation_books_lent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_navigation_books_lentActionPerformed(evt);
            }
        });

        user_navigation_GO_BACK.setText("GO BACK ");
        user_navigation_GO_BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_navigation_GO_BACKActionPerformed(evt);
            }
        });

        jButton1.setText("USER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(user_navigation_branch)
                                .addGap(18, 18, 18)
                                .addComponent(user_navigation_book_details))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(user_navigation_book)
                                .addGap(40, 40, 40)
                                .addComponent(user_navigation_author)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user_navigation_books_lent)
                            .addComponent(user_navigation_branch_book_details))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(39, 39, 39)
                .addComponent(user_navigation_GO_BACK)
                .addGap(139, 139, 139))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_navigation_branch)
                    .addComponent(user_navigation_book_details)
                    .addComponent(user_navigation_branch_book_details))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_navigation_book)
                    .addComponent(user_navigation_author)
                    .addComponent(user_navigation_books_lent))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_navigation_GO_BACK)
                    .addComponent(jButton1))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_navigation_books_lentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_navigation_books_lentActionPerformed
        books_lent b=new books_lent();
        this.hide();
        b.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_user_navigation_books_lentActionPerformed

    private void user_navigation_GO_BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_navigation_GO_BACKActionPerformed
         MainForm m=new MainForm();
         this.hide();
         m.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_user_navigation_GO_BACKActionPerformed

    private void user_navigation_branchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_navigation_branchActionPerformed
        // TODO add your handling code here:
        Branch b=new Branch();
        this.hide();
        b.setVisible(true);
        
    }//GEN-LAST:event_user_navigation_branchActionPerformed

    private void user_navigation_book_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_navigation_book_detailsActionPerformed
        // TODO add your handling code here:
         project b=new project();
        this.hide();
        b.setVisible(true);
    }//GEN-LAST:event_user_navigation_book_detailsActionPerformed

    private void user_navigation_branch_book_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_navigation_branch_book_detailsActionPerformed
        // TODO add your handling code here:
        branch_b_d b=new branch_b_d();
        this.hide();
        b.setVisible(true);
    }//GEN-LAST:event_user_navigation_branch_book_detailsActionPerformed

    private void user_navigation_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_navigation_bookActionPerformed
        // TODO add your handling code here:
        fines b=new fines();
        this.hide();
        b.setVisible(true);
    }//GEN-LAST:event_user_navigation_bookActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        User b=new User();
        this.hide();
        b.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void user_navigation_authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_navigation_authorActionPerformed
        // TODO add your handling code here:
        AUTHOR b=new AUTHOR();
        this.hide();
        b.setVisible(true);
    }//GEN-LAST:event_user_navigation_authorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton user_navigation_GO_BACK;
    private javax.swing.JButton user_navigation_author;
    private javax.swing.JButton user_navigation_book;
    private javax.swing.JButton user_navigation_book_details;
    private javax.swing.JButton user_navigation_books_lent;
    private javax.swing.JButton user_navigation_branch;
    private javax.swing.JButton user_navigation_branch_book_details;
    // End of variables declaration//GEN-END:variables
}
